apiVersion: v1
baseDomain: ngplab.ocp4.lan
proxy:
  httpProxy: http://10.92.0.51:8080
  httpsProxy: http://10.92.0.51:8080
  noProxy: ngplab.lan,192.168.1.0/24
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ngplab # Cluster name
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: ''
sshKey: ''
